server:
  port: 8082

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    # 前端解析目录
#    view:
#      prefix: /WEB-INF/page/
#      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sims?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB #单个文件上传大小
      max-request-size: 600MB #连续上传文件大小
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
logging:
  level:
    org.thymeleaf: info

mybatis:
  # MyBatis解析设置
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.haims.pojo

file:
  path: "E:\\project\\idea-project\\ChaoShiJinXiaoCun2\\src\\main\\resources\\static\\image\\" #存储路径